// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/image.proto

package image

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImageRequest struct {
	Images               []*ImageRequest_Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ImageRequest) Reset()         { *m = ImageRequest{} }
func (m *ImageRequest) String() string { return proto.CompactTextString(m) }
func (*ImageRequest) ProtoMessage()    {}
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_042638d41ebcabe6, []int{0}
}

func (m *ImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageRequest.Unmarshal(m, b)
}
func (m *ImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageRequest.Marshal(b, m, deterministic)
}
func (m *ImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRequest.Merge(m, src)
}
func (m *ImageRequest) XXX_Size() int {
	return xxx_messageInfo_ImageRequest.Size(m)
}
func (m *ImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRequest proto.InternalMessageInfo

func (m *ImageRequest) GetImages() []*ImageRequest_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type ImageRequest_Image struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Encoded              string   `protobuf:"bytes,2,opt,name=encoded,proto3" json:"encoded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageRequest_Image) Reset()         { *m = ImageRequest_Image{} }
func (m *ImageRequest_Image) String() string { return proto.CompactTextString(m) }
func (*ImageRequest_Image) ProtoMessage()    {}
func (*ImageRequest_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_042638d41ebcabe6, []int{0, 0}
}

func (m *ImageRequest_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageRequest_Image.Unmarshal(m, b)
}
func (m *ImageRequest_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageRequest_Image.Marshal(b, m, deterministic)
}
func (m *ImageRequest_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRequest_Image.Merge(m, src)
}
func (m *ImageRequest_Image) XXX_Size() int {
	return xxx_messageInfo_ImageRequest_Image.Size(m)
}
func (m *ImageRequest_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRequest_Image.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRequest_Image proto.InternalMessageInfo

func (m *ImageRequest_Image) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ImageRequest_Image) GetEncoded() string {
	if m != nil {
		return m.Encoded
	}
	return ""
}

func init() {
	proto.RegisterType((*ImageRequest)(nil), "ImageRequest")
	proto.RegisterType((*ImageRequest_Image)(nil), "ImageRequest.Image")
}

func init() { proto.RegisterFile("proto/image.proto", fileDescriptor_042638d41ebcabe6) }

var fileDescriptor_042638d41ebcabe6 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcc, 0x4d, 0x4c, 0x4f, 0xd5, 0x03, 0xb3, 0x95, 0x8a, 0xb8, 0x78, 0x3c, 0x41,
	0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x6d, 0x2e, 0x36, 0xb0, 0x74, 0xb1, 0x04,
	0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xb0, 0x1e, 0xb2, 0x34, 0x94, 0x03, 0x55, 0x22, 0x65, 0xca,
	0xc5, 0x0a, 0x16, 0x10, 0x12, 0xe2, 0x62, 0x29, 0x2d, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x53, 0xf3, 0x92, 0xf3, 0x53, 0x52, 0x53, 0x24,
	0x98, 0xc0, 0xc2, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0x52, 0x81, 0xeb, 0x8f, 0x00, 0x00, 0x00,
}
